### ISSUE TITLE
Wrong score calculation in variant of most crossing 

### ISSUE THREAD

**Issue by fraknoiadam** [quibbble/go-tsuro#1]
Hi,

I've found a bug when you calculate the score in the variant of most crossing.

https://github.com/quibbble/go-tsuro/blob/a30d5867d5ecc0c5cd35dfb1d8f2e1469d43e240/state.go#L326-L349

This algorithm runs incorrectly in the following example, because it should worth 4=1+3 points, but it gives only 3=1+2 points:

![image](https://github.com/quibbble/go-tsuro/assets/22480910/30982557-81ae-4874-b2ab-1fcd4cd32653)

Solution: Instead of choosing the highest element in `pathScores` you have to sum the scores in `pathScores` and divide by two.

This algorithm will clearly work for all tiles except the following one:
![image](https://github.com/quibbble/go-tsuro/assets/22480910/bd6ef41f-7e5e-408f-a297-61ec41ff1187)

Here you have more options for how many points it is worth, when 3 or 4 paths (of the same player) are crossing in the middle of tile.

- If 3 paths are crossing in the middle of tile, it should worth 3 points, and if 4 paths then 6 points.
- If 3 paths are crossing in the middle of tile, it should worth 2 points, and if 4 paths then 3 points.
- It should always worth 1 point.

The first case does not need any further implementation, but the other two one should handle this special tile.

I personally think that the first option is the fairest, because if you move the lines a bit so, that there will be no 3 paths of them, that intersects in one point, then there will be 6 points.

**Comment by freglyc** [comment]
Hey @fraknoiadam thanks for opening this issue. I agree that the first option is the fairest and probably the best path forward. If you would like to take a stab at fixing this and open a PR I'd appreciate the help. Otherwise I'll look into fixing this when I have some spare time. 

Either way thanks for the detailed writeup and help in improving Quibbble!

**Comment by freglyc** [comment]
The [change](https://github.com/quibbble/go-tsuro/commit/b1ca787e23d664b92a5fe80103c044a72f1a6c60) has been made and is now deployed. Thanks again for posting this issue.
